version: "3.5"
services:  

  #service for api
  userservice: #can be any name, service name
    image: loginapi
    ports:
      - "5050:80"
    environment:
      MONGODB_CONNECTIONSTRING: "mongodb://mongo_auth:27017"
      consulserver: "http://consul:8500"
    depends_on:
      - consul
      - mongo_auth

  # service onemap api
  onemapservice:
    image: onemapapi
    ports:
      - "5100:80"
    environment:
    # SQL_DB: "Server=sqldb;Initial Catalog=FavouritesDB;User Id=sa;password=temus@123" 
      #use sql server running inside docker, not our local host. Same as container name
      consulserver: "http://consul:8500"
    depends_on:
      - consul 

  # fav service api
  favservice:
    image: favoritesapi
    ports:
      - "5200:80"
    environment:
      SQL_DB: "Server=sqldb;Initial Catalog=FavouritesDB;User Id=sa;password=temus@123"
      consulserver: "http://consul:8500"
    depends_on:
      - consul

  # taxi service api
  taxiservice:
    image: taxiapi
    ports:
      - "5250:80"
    environment:
      consulserver: "http://consul:8500"
    depends_on:
      - consul 

  # email service api
  emailservice:
    image: emailapi
    ports:
      - "5300:80"
    environment:
      consulserver: "http://consul:8500"
    depends_on:
      - consul 

  #service for sql database
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=temus@123 #anything we want
      - ACCEPT_EULA=Y #end user license agreement

  # service for mongo database
  mongo_auth:
    image: mongo
    ports:
      - "27017:27017"

  # api gateway
  apigateway:
    image: apigateway
    ports:
      - "5000:80"

  # running the consul
  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0

 # sqldbf:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - "1434:1433"
  #   environment:
  #   - SA_PASSWORD=pass@123
  #   - ACCEPT_EULA=Y

  # frontend
  frontend:
    image: frontend
    ports:
      - "4200:80"